name: Downloader Step 1

on:
  workflow_dispatch:
    inputs:
      activation_code:
        description: 'کد فعالسازی'
        required: false
      url:
        description: 'لینک دانلود'
        required: false

jobs:
  inputs-test:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Activation Code: ${{ github.event.inputs.activation_code }}"
          echo "URL: ${{ github.event.inputs.url }}"
